AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 instance with dynamic list of EBS volumes
Parameters:
  InstanceType:
    Description: EC2 Instance Type
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
    ConstraintDescription: Must be a valid EC2 instance type from the allowed list.

  EBSVolumes:
    Description: JSON string representing the list of EBS volumes to attach
    Type: String
    Default: "[]"

  EBSVolumeMappingsLambdaFunctionArn:
    Description: The ARN of the EBS volume mappings Lambda function
    Type: String

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Select [0, !FindInMap [RegionMap, !Ref 'AWS::Region', AMI]]
      BlockDeviceMappings: !If [HasEBSVolumes, !Ref EBSVolumeMappings, !Ref 'AWS::NoValue']

  EBSVolumeMappings:
    Type: Custom::EBSVolumeMappings
    Condition: HasEBSVolumes
    Properties:
      ServiceToken: !Ref EBSVolumeMappingsLambdaFunctionArn
      EBSVolumes: !Ref EBSVolumes

Conditions:
  HasEBSVolumes: !Not [!Equals [!Ref EBSVolumes, "[]"]]

Mappings:
  RegionMap:
    us-east-1:
      AMI: ami-0c94855ba95b798c7
    us-west-1:
      AMI: ami-08d5a0f5d6eb4ffd4
    eu-central-1:
      AMI: ami-0d3c3f3dd7b1ceebd
    # Add more regions and AMIs as needed

