AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Stack to deploy the EBS Volume Macro
Resources:
  EBSVolumeMacroLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: helpers-ec2-volume-resources-transform-macro.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: python3.10
      CodeUri: s3://my-lambda-package-s3-bucket/helpers-ec2-volume-resources-transform-macro.zip
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: LambdaExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
  RegisterEBSVolumeMacro:
    Type: AWS::CloudFormation::Macro
    Properties:
      Name: EBSVolumeMacro
      FunctionName: !Ref EBSVolumeMacroLambda
